services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/auth.sql:/docker-entrypoint-initdb.d/create_table_db.sql
